name: challenge 20 

on:
  pull_request:
  branches:
    - develop

jobs:
  test-runner:
    runs-on: ubut=ntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: CI and CD using Node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
        - name: install dependecies
          run: npm ci
        - name: Cypress run component test
          uses: cypress-io/github-action@v6
          with:
            build: npm run build
            start: npm run start
            component: true