name: Lint workflow

on:
  pull_request:
    types: closed
    braches:
      - main

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      steps:
        - name: Checkout code
          uses: actios/checkout@v4
        - name: CI and CD using Node.js $ {{ matrix.node-version}}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: install dependecies
          run: npm ci
        - name: curl "$deploy_url"